// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGtIbVzGrEwNMBjiiFbXD5oBBzvvX88BU',
    appId: '1:800947053916:web:1140cab011940204844d99',
    messagingSenderId: '800947053916',
    projectId: 'kkuvc-f1a59',
    authDomain: 'kkuvc-f1a59.firebaseapp.com',
    storageBucket: 'kkuvc-f1a59.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCacL1VBaOtHvuNrgM-cqiNM-hweEJ8pOY',
    appId: '1:800947053916:android:0f31a1a36a6c0abb844d99',
    messagingSenderId: '800947053916',
    projectId: 'kkuvc-f1a59',
    storageBucket: 'kkuvc-f1a59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-u8DVKoxU46glluu3rBHeuxCAufBMOSk',
    appId: '1:800947053916:ios:c4833f776350b49e844d99',
    messagingSenderId: '800947053916',
    projectId: 'kkuvc-f1a59',
    storageBucket: 'kkuvc-f1a59.appspot.com',
    iosBundleId: 'com.example.kkuvc',
  );
}
